# Build Stage
FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o main cmd/web/main.go

# Run stage
FROM alpine:3.16
WORKDIR /app
COPY --from=builder /app/main .
COPY /internal/db/migration ./internal/db/migration

EXPOSE 80
CMD ./main -url=postgresql://postgresql://{user}:{password}@{db url}/{db name}?sslmode=disable -port=0.0.0.0:80